### ISSUE TITLE
newrelic service plans limitation 

### ISSUE THREAD

**Issue by kkdhasan** [newrelic/newrelic-pcf-agent-tile#8]
Hi, 
 
There are about 300+ service plans in the NR service broker in our PCF foundation, totaling 45910 bytes in variable size on NRPLANS. The NRPLANS variable is expected to be encrypted and pushed into the Tanzu CCDB. After encryption, the size would be greater than 65KB. By then, we would have exceeded the CCDB data type and application environment variable size limits.

Getting the following error message, after the addition of a New Relic service plan:
"Failed Server error, status code: 500, error code: 10011, message: Database error"

It was suggested that the variable size be decreased. Even if we shorten the plan description, the problem will continue to be reported. I would like to understand why the variable size increased after it was encrypted and what options there are to reduce the variable size.

Thanks,
Kanna

**Comment by jbeveland27** [comment]
Thanks for reporting @kkdhasan - we're looking into it.

**Comment by miransar** [comment]
@kkdhasan As you rightly said, this is a limitation on the CCDB side as all environment variables are being serialized to one column of the database, and the size of the sum of all the environment variables is limited to that of the column. 

This issue has been raised to PCF in the past as well-> [cloud_controller_ng/issues/1148](https://github.com/cloudfoundry/cloud_controller_ng/issues/1148) and [cloud_controller_ng/issues/1555](https://github.com/cloudfoundry/cloud_controller_ng/issues/1555). As mentioned in the issue, the outcome was to only make the error more descriptive instead of just "Database error" (which still seems to be showing the same error) and not make any changes to limits as they are intentional and required. 

In terms of options to reduce the size of variables, there are no direct solutions at the moment. However, I suggest to open an issue in the [cloud_controller_ng](https://github.com/cloudfoundry/cloud_controller_ng/issues) repository for the whole community to look at and discuss. I would also suggest to explore [CredHub](https://docs.vmware.com/en/Tile-Developer-Guide/3.0/tile-dev-guide/create-credhub-vars.html) as it allows to store and fetch variables and might suit your use case. Meanwhile, I will continue to look deeper into this.

**Comment by miransar** [comment]
Since there hasn't been any activity on this issue for three months, we're going to close it for now. 

Feel free to reopen if you have more information or encounter the issue again.
